[build]
  command = "cd frontend && npm install && npm run build"
  functions = "netlify/functions"
  publish = "frontend/build"

[dev]
  command = "cd frontend && npm start"
  port = 3000
  targetPort = 8888
  publish = "frontend/build"
  autoLaunch = true
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
